version: '3.7'
services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ACCESS_KEY=zgoksxu7L9f0SUm3sara
      - MINIO_SECRET_KEY=bMVJnQUk3UrYUFmzMRxcovlu4HA9UxOKZAcRSRUi
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_CONSOLE_ADDRESS=:9001
    volumes:
      - .//Users/xiabai/workspace/tiny/:/data  # 使用主机上的相对路径
      - ./credentials.json:/etc/minio/credentials.json
      # 或者使用绝对路径
      # - /path/to/your/directory:/data
    command: server /data --console-address ":9001"
    restart: always