version: '3.7'
services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      # - MINIO_ACCESS_KEY=te3eE6tUkdapkD84ubJr
      # - MINIO_SECRET_KEY=fmttTkdBfUcFYV8gRtxm2mvgU3CBBfxPiexlTfK6
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_CONSOLE_ADDRESS=:9001
    volumes:
      # - ./credentials.json:/etc/minio/credentials.json
      - ../data/:/data 
     
      # 或者使用绝对路径
      # - /path/to/your/directory:/data
    command: server /data --console-address ":9001"
    restart: always