version: '3.8'
services:
  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ${MINIO_DATA_PATH}:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server --console-address ":9001" /data
    restart: always
    networks:
      - sprout_network

  postgres:
    image: postgres:15-alpine
    container_name: sprout_postgres
    restart: always
    environment:
      POSTGRES_USER: sprout_admin
      POSTGRES_PASSWORD: sprout_pwd
      POSTGRES_DB: sprout_model
    ports:
      - "5432:5432"
    command: >
      postgres -c 'max_connections=100'
               -c 'shared_buffers=128MB'
               -c 'work_mem=4MB'
               -c 'maintenance_work_mem=64MB'
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - sprout_network

volumes:
  pg_data:

networks:
  sprout_network:
