version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: sprout_postgres
    restart: always
    environment:
      POSTGRES_USER: sprout_admin
      POSTGRES_PASSWORD: sprout_pwd
      POSTGRES_DB: sprout_model
    ports:
      - "5432:5432"
    command: >
      postgres -c 'max_connections=100'
               -c 'shared_buffers=128MB'
               -c 'work_mem=4MB'
               -c 'maintenance_work_mem=64MB'
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - sprout_network

volumes:
  pg_data:

networks:
  sprout_network:
