version: '3.8'
services:
  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ${MINIO_DATA_PATH}:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server --console-address ":9001" /data
    restart: always
    networks:
      - sprout_network

  postgres:
    image: postgres:15-alpine
    container_name: sprout_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    command: >
      postgres -c 'max_connections=100'
               -c 'shared_buffers=128MB'
               -c 'work_mem=4MB'
               -c 'maintenance_work_mem=64MB'
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/migrations:/migrations
      - ./db/start-postgres.sh:/start-postgres.sh
    networks:
      - sprout_network

  sprout:
    image: ghcr.io/tinybloom/sprout:0.3
    container_name: sprout
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      MINIO_URI: minio:9000
    ports:
      - "5001:5001"
    depends_on:
      - minio
      - postgres
    networks:
      - sprout_network


volumes:
  pg_data:

networks:
  sprout_network:
